language: python
sudo: required
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"
env:
  #- NEO4J_VERSION="3.0.10"  # unsupported by neo4j.com (DEC18)
  #- NEO4J_VERSION="3.1.7"   # unsupported by neo4j.com (DEC18)
  #- NEO4J_VERSION="3.2.13"
  - NEO4J_VERSION="3.3.9"
  - NEO4J_VERSION="3.4.10"
  - NEO4J_VERSION="3.5.0"
install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - curl -L http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
  - pip install tox-travis
before_script:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - sleep 10
script:
  - tox
notifications:
  email: false

